name: cmake-configure-build-test

inputs:
  use-emscripten:
    type: boolean
    default: false
  test:
    type: boolean
    default: true

runs:
  using: composite
  steps:
    - if: inputs['use-emscripten'] == 'true'
      name: Setup Emscripten SDK
      uses: mymindstorm/setup-emsdk@v14

    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Configure ${{ inputs['use-emscripten'] == 'true' && 'using emcmake' || '' }}
      run: ${{ inputs['use-emscripten'] == 'true' && 'emcmake' || '' }} cmake -B build
      shell: bash

    - name: Build
      run: cmake --build build
      shell: bash

    - if: inputs.test == 'true'
      name: Test
      run: ctest --test-dir build --verbose --output-on-failure --no-tests=error
      shell: bash